-- MySQL Script generated by MySQL Workbench
-- jue 30 nov 2017 10:25:25 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compras` DEFAULT CHARACTER SET utf8 ;
USE `compras` ;

-- -----------------------------------------------------
-- Table `compras`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`cliente` ;

CREATE TABLE IF NOT EXISTS `compras`.`cliente` (
  `idcliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`producto` ;

CREATE TABLE IF NOT EXISTS `compras`.`producto` (
  `idproducto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`administrador` ;

CREATE TABLE IF NOT EXISTS `compras`.`administrador` (
  `idAdministrador` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`factura` ;

CREATE TABLE IF NOT EXISTS `compras`.`factura` (
  `numfactura` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`numfactura`),
  INDEX `fk_factura_cliente1_idx` (`cliente_idcliente` ASC),
  INDEX `fk_factura_Administrador1_idx` (`Administrador_idAdministrador` ASC),
  INDEX `fk_factura_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `compras`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `compras`.`administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `compras`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
